# Generated by Django 3.1.7 on 2021-03-05 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('owdr_app', '0002_auto_20210304_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Liczba worków')),
                ('address', models.CharField(max_length=120, verbose_name='Ulica i numer domu')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Numer telefonu')),
                ('city', models.CharField(max_length=34, verbose_name='Miasto')),
                ('zip_code', models.CharField(max_length=6, verbose_name='Kod pocztowy')),
                ('pick_up_date', models.DateField(verbose_name='Data odbioru')),
                ('pick_up_time', models.TimeField(verbose_name='Godzina odbioru')),
                ('pick_up_comment', models.TextField(verbose_name='Komentarz')),
            ],
        ),
        migrations.CreateModel(
            name='DonationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owdr_app.category')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owdr_app.donation')),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='categories',
            field=models.ManyToManyField(through='owdr_app.DonationCategory', to='owdr_app.Category', verbose_name='Kategoria'),
        ),
        migrations.AddField(
            model_name='donation',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owdr_app.institution', verbose_name='Instytucja'),
        ),
        migrations.AddField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
