# Generated by Django 3.1.7 on 2021-03-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owdr_app', '0003_auto_20210305_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(default=False, null=True, verbose_name='Odebrane'),
        ),
    ]
